<p class="manual-intro">Billing manages the business's trial and paid subscription access. It is separate from customer sale payments. Package requests need MKPOS office approval; uploading proof is not immediate activation.</p>
<h2 id="status">Check your current access</h2>
<ol><li>Sign in as the owner and open <strong>Billing</strong>.</li><li>Read Current package, Billing status, Access valid until and any remaining-days information.</li><li>Check whether a package request is already awaiting approval before submitting another.</li><li>Use Refresh after receiving an activation or renewal confirmation.</li></ol>
<p>New businesses begin with a one-month free trial. Use the end date shown for your account rather than calculating it from a screenshot or another shop. Backup download and restore require a paid plan. After access expires, business actions may be blocked until the subscription is valid again.</p>
<h2 id="choose">Choose a package</h2>
<p>Compare the packages listed in Billing or on the public Package plans page. Check the name, currency, price, number of access days and stated features. The public page shows active, public packages, not every internal plan. No published packages means availability must be confirmed with the MKPOS office; it does not mean unlimited free access.</p>
<p>A term shown as 90 days is 90 days of access, not an assumed three calendar months. Do not assume unpublished device, staff or product limits.</p>
<h2 id="request">Submit payment evidence</h2>
<ol><li>Choose <strong>Request package</strong>, or <strong>Request renewal</strong> for the applicable current package.</li><li>In the request form, select one of the available payment methods and carefully read its displayed recipient details.</li><li>Make the actual payment using the appropriate payment service. MKPOS's request form does not itself transfer funds.</li><li>Attach the requested payment screenshot and include a helpful reference or message where offered. Check that the image is readable and belongs to this payment.</li><li>Review the package and evidence, then submit once.</li><li>Confirm the request shows as pending. Keep your original payment evidence until activation is verified.</li></ol>
<h2 id="approval">Verify activation or renewal</h2>
<p>A pending notice means the office has not yet completed payment confirmation. After approval, refresh Billing and verify the Current package, Billing status and Access valid until. Completed assignments and renewals appear in Billing history with date, package, term, reference and amount.</p>
<p>If a request is rejected or remains unresolved, read any feedback and contact the office with the reference and payment details. Do not pay twice solely because the screen still says pending.</p>
<h2 id="problems">Common billing problems</h2>
<ul><li><strong>No payment method is available:</strong> contact the MKPOS office before attempting a package request.</li><li><strong>Request pending:</strong> wait for confirmation or follow up using the existing reference.</li><li><strong>Active subscription required:</strong> ask the owner to inspect Billing; preserve pending offline sales and do not reset app data.</li><li><strong>Backup disabled during trial:</strong> it is a plan restriction, not a printer or browser problem.</li></ul>
