<p class="manual-intro">A customer account connects named customers to credit sales and subsequent payments. Keep each customer's identity clear: collecting from the wrong account can leave one person appearing unpaid and another overpaid.</p>
<h2 id="create">Create a customer</h2>
<ol><li>Open <strong>Customers → Add Customer</strong>.</li><li>Enter Customer Name and, where available, Phone, Address and Note. Include enough information to distinguish people with the same name.</li><li>Save, then search by name or phone and confirm the record. Reuse this customer on future sales rather than creating a new account each visit.</li></ol>
<h2 id="credit">Make a credit sale</h2>
<p>At online checkout, select the customer, enter the real payment received and review Unpaid. Any remaining amount is credit. A fully unpaid sale has paid amount 0; a part-paid sale has a payment smaller than the total. Do not select a random customer just to bypass the unpaid warning.</p>
<p>Example: a customer buys 10,000 Ks of goods and pays 4,000. The new unpaid amount is 6,000. Their account can also include earlier sales and payments, so the current balance need not equal this single receipt's unpaid amount.</p>
<h2 id="collect">Record a later repayment</h2>
<ol><li>Open the customer's details and inspect the name, phone, current balance and sales history.</li><li>Find the payment form. Choose <strong>Customer pays shop</strong> when collecting money.</li><li>Enter the amount actually received and the Payment method. Add a Note with a receipt or transfer reference and the purpose.</li><li>Select <strong>Save payment</strong> once and wait for success.</li><li>Check the payment history and new balance. A 2,000 payment against the 6,000 example leaves 4,000, assuming no other activity.</li></ol>
<div class="docs-note"><strong>Do not record the checkout payment twice.</strong> The 4,000 paid during the sale is already recorded by checkout. The customer payment form is for later money movement, not a second entry of the same payment.</div>
<h2 id="direction">Money paid back to a customer</h2>
<p><strong>Shop pays customer</strong> records money going out of the shop to that customer. It is the opposite direction from a repayment. Enter a clear reason and obtain the owner's approval. Recording money movement is not, by itself, a product return or stock adjustment. If goods also change hands, the owner must review the linked sale and inventory separately.</p>
<h2 id="statement">Review history and statements</h2>
<p>Open the customer details, use the available sales or payment history sections, choose From and To dates, and select Apply. Clear resets the filters. Print the customer statement using the available statement action and verify its customer, dates and balances before sharing it.</p>
<p>Statements and other account documents may use A4 system printing even if sale receipts use a thermal device. Account history contains personal and financial information; send it only to the intended customer or authorized staff.</p>
<h2 id="correct">Correct a mistake</h2>
<p>Use Edit customer for contact details. For a payment error, locate that payment and use the authorized Edit payment or Delete payment action, then verify the resulting balance. Do not delete a customer to remove a debt, and do not make a false payment to force a balance to zero. If the system refuses deletion because records exist, preserve the history and ask the owner how to proceed.</p>
<p>For a balance dispute, compare receipt numbers, payment direction, dates and actual transfer evidence. A filtered history may hide older activity; inspect the full history before changing anything.</p>
