<p class="manual-intro">Backups protect recorded business data. Updates replace application code. Restore replaces business records. These are different operations, and none should start with unsynchronized sales forgotten on a device.</p>
<h2 id="contains">Know what a business backup contains</h2>
<p>The Data screen's business backup includes products, prices, customers, suppliers, sales, purchases, payments, expenses, stock history and shop settings for the current business. Accounts, passwords, staff roles and subscription records are <strong>not included</strong>.</p>
<p>Local native printer profiles and unsynchronized device-only sales should not be treated as part of the server backup. A product CSV, report CSV, receipt PDF or screenshot is not a complete business backup.</p>
<h2 id="download">Download a backup</h2>
<ol><li>Ask cashiers to finish ongoing work and inspect pending sales on every offline device.</li><li>Synchronize pending work and verify the corresponding online records.</li><li>Sign in with the required authority and open <strong>Settings → Data</strong>. Backup download and restore require a paid plan.</li><li>Check the database status and business identity, then use the backup download action.</li><li>Wait for the download to complete. Locate the downloaded <strong>.mkpos-backup</strong> file and check its date and that it is not empty.</li><li>Keep a dated copy in a protected location separate from the checkout device. Retain more than one generation so a recent mistake does not replace your only good backup.</li></ol>
<div class="docs-note">Backup files contain business and customer information. Restrict access. Checking that a file exists is useful, but full recovery confidence requires a controlled restore test coordinated by the person managing the system—not a trial restore over a live shop.</div>
<h2 id="restore">Restore only when deliberately recovering data</h2>
<p>Restore is not a refresh button, an import of a few products or a safe way to compare an old report. It can replace current business records with the selected backup and discard newer work.</p>
<ol><li>Obtain the owner's approval. Decide why restore is needed and which business and backup date are correct.</li><li>Stop all tills from writing new records. Check each device for pending offline sales; do not assume they will safely merge after restore.</li><li>Download and preserve a backup of the current state before proceeding, if the system is available.</li><li>Open Settings → Data, choose the intended backup file and verify its filename and origin.</li><li>Type the required <strong>RESTORE</strong> confirmation and enter the Admin PIN if requested.</li><li>Read the warning, start restore once and wait. If the result is uncertain, ask the administrator to inspect it before retrying.</li><li>Verify products, counts, recent transactions, account balances and settings afterward. Accounts, staff roles and subscription records are not restored from this file.</li><li>Coordinate refresh of every device before reopening the shop. Investigate stale caches and pending work rather than blindly synchronizing them.</li></ol>
<h2 id="update">Update Windows or Android safely</h2>
<ol><li>Finish active prints and saves. Synchronize pending sales and keep a recent backup.</li><li>Check the current application version in About and obtain the intended published build from the MKPOS download page or your administrator.</li><li>Follow the installer or package instructions. Do not delete old data folders or uninstall to solve an update problem.</li><li>Android updates require a compatible signing certificate. If installation reports a signature mismatch, stop and contact the administrator; uninstalling can remove local data.</li><li>After updating, confirm business identity, products, pending count, version and device printer settings. Run one test receipt before serving customers.</li></ol>
<h2 id="routine">A simple maintenance routine</h2>
<p>At closing, check synchronization and take a backup when permitted. Before an important import or record correction, keep a recoverable copy. Periodically verify backup storage access and coordinate a recovery test. Never clear browser storage or app data as a general troubleshooting step when local work may remain.</p>
