<p class="manual-intro">Expenses record the shop's operating costs, such as rent, electricity or transport. Stock bought for resale belongs in New Purchase; a supplier debt repayment belongs in supplier payments. Recording either again as an expense can make reports misleading.</p>
<h2 id="record">Record an expense</h2>
<ol><li>Open <strong>Expenses</strong> and choose its add action.</li><li>Check <strong>Date</strong>, then enter a short, specific <strong>Title</strong>, such as “September shop electricity”.</li><li>Choose or enter <strong>Category</strong>. Use consistent names so similar costs appear together in reports.</li><li>Enter the positive <strong>Amount</strong> and choose <strong>Payment</strong>, meaning the method used to pay.</li><li>Add a <strong>Note</strong> with the bill number, payee or explanation.</li><li>Review and save once. Find the saved expense in the list and check its date, category and amount.</li></ol>
<h2 id="example">Example and common classification mistakes</h2>
<p>For a 25,000 Ks electricity bill paid in cash, choose an appropriate electricity or utilities category, enter 25,000 and select Cash. This records a business running cost; it does not add inventory.</p>
<ul><li>Buying bottled water to resell: use New Purchase, not Expenses.</li><li>Paying an earlier supplier bill: use Record Supplier Payment, not a second purchase or expense.</li><li>Collecting customer debt: use the customer's payment form, not a negative expense.</li><li>If one real payment covers different purposes, ask the owner how to split the records without counting the money twice.</li></ul>
<h2 id="find">Search and filter expenses</h2>
<p>Search by Title, Category or Note. Use Category, Payment and From / To filters to narrow the period; apply the filters using the screen's filter action. Check the displayed dates and clear filters when a record appears missing. Use the list's page controls or scrolling to see the remaining records.</p>
<h2 id="edit">Correct or remove a record</h2>
<ol><li>Find the exact expense and open Edit expense.</li><li>Compare it with the original bill before changing the date, amount, method or description.</li><li>Save and verify the list and relevant reporting period.</li><li>Use Delete expense only for a genuinely incorrect or duplicate record and only with the required authority. Read the confirmation first.</li></ol>
<div class="docs-note">A deleted expense no longer contributes to the same report totals. Keep the supporting bill and the reason for the correction. Do not delete a real expense just to improve the displayed profit estimate.</div>
