<p class="manual-intro">Offline POS is a continuity tool for supported local sales when the server cannot be reached. It does not turn every management screen into an offline feature. Prepare each device while online before depending on it.</p>
<h2 id="prepare">Prepare a device in advance</h2>
<ol><li>Sign into the correct business while the server is available and allow the application to load the product catalogue.</li><li>Open Offline POS where offered and confirm that the expected cached products and prices appear. An empty cache cannot serve as a live catalogue.</li><li>Configure this device's printer and test it. In the Windows offline interface, open Printer settings from its button/drawer; close the drawer when finished.</li><li>Check that the account and subscription allow offline use. Do not assume a new installation can sign in for the first time without internet.</li><li>Agree with the owner how staff should handle limited stock when multiple tills are offline.</li></ol>
<h2 id="sell">Complete an offline sale</h2>
<ol><li>Confirm the Offline POS heading and business/user identity.</li><li>Search or scan a cached product, select the intended price and quantities, and inspect the cart.</li><li>Enter an allowed discount and payment method. Offline checkout supports eligible <strong>fully paid</strong> sales; customer credit is unavailable offline.</li><li>Verify real payment, select <strong>Complete offline sale</strong> once and wait for the local completion result.</li><li>Check the pending-sale count and the saved invoice/receipt list. Print the saved receipt if required.</li></ol>
<div class="docs-note">“Server available” does not mean all pending sales have synchronized. A printed receipt also does not prove synchronization. Check the queue and the server's transaction history.</div>
<h2 id="stock">Understand stock and price limitations</h2>
<p>Offline products and prices are cached copies. Another till may sell the same stock, and an owner may change a price while your device is disconnected. Server stock is not checked until synchronization. Confirm physical availability and investigate conflicts when reconnecting.</p>
<p>Do not promise that an offline quantity is a live business-wide stock count. If a required customer-credit or management action is unavailable, wait for an authorized online workflow instead of inventing a cash sale or editing storage.</p>
<h2 id="sync">Reconnect and verify</h2>
<ol><li>Restore internet and server access. Keep the app and the account that owns the pending sales available.</li><li>Use <strong>Go online & sync</strong> or the available sync action.</li><li>Wait for the result. Review individual failures rather than repeatedly clicking Sync.</li><li>Confirm that the pending count reaches zero for successfully synchronized sales. Investigate any remaining item.</li><li>Open online Transactions and match the receipts and totals. Refresh Reports after synchronization.</li></ol>
<h2 id="protect">Protect pending sales</h2>
<ul><li>Do not clear browser storage, reset app data or uninstall while sales are pending.</li><li>Do not switch accounts, wipe a device or replace an installation to solve a sync error without first safeguarding its queued work.</li><li>A server business backup does not include sales that exist only in the device's pending queue.</li><li>Record error text, receipt/reference identifiers and pending counts before contacting support. Do not share passwords or full customer data publicly.</li><li>If a sale might already have reached the server, find its transaction before manually entering it online. Otherwise you can duplicate it.</li></ul>
<h2 id="blocked">When synchronization is blocked</h2>
<p>Check server access, sign-in/session validity, subscription status and the reported item or stock error. Give the owner the exact message and affected receipt. Restore connectivity and authorized access; do not change device time, manufacture stock or delete queue records to bypass the problem.</p>
