<p class="manual-intro">First identify which MKPOS application you are using and how the printer connects. A printer brand alone does not determine compatibility. Canon and Epson make different kinds of devices; direct thermal printing needs a compatible ESC/POS printer, not simply any device with Wi-Fi or Bluetooth.</p>
<h2 id="choose">Choose your printing method</h2>
<div class="docs-table-wrap" role="region" aria-label="Printing compatibility" tabindex="0"><table class="docs-table"><caption>Use the matching method for your application and printer.</caption><thead><tr><th>Application</th><th>Normal printer / PDF</th><th>Direct thermal</th></tr></thead><tbody><tr><th scope="row">Web browser</th><td>Browser print dialog and a system-installed destination.</td><td>No built-in direct raw TCP or Bluetooth connection in the current web printing path. A thermal printer can use its system driver through the browser dialog.</td></tr><tr><th scope="row">Windows app</th><td>Compatible installed Windows driver, or a PDF destination.</td><td>ESC/POS TCP or paired Bluetooth Classic using an outgoing COM port.</td></tr><tr><th scope="row">Android APK</th><td>Android print dialog, compatible print service or Save as PDF.</td><td>ESC/POS TCP or paired Bluetooth Classic SPP. BLE-only and direct USB are not supported.</td></tr></tbody></table></div>
<h2 id="installed">Windows: installed printer</h2>
<ol><li>Install the printer in Windows with its compatible driver. Confirm it can print from Windows before configuring MKPOS.</li><li>Open <strong>Settings → Printer</strong>. Choose <strong>Installed printer — Canon / Epson / thermal / PDF</strong>.</li><li>Select <strong>Refresh Printers</strong> and choose Printer Name. Leaving the name blank uses the Windows default printer.</li><li>Choose Receipt Paper: A4 for office paper, or the width matching the loaded receipt roll. Match the driver's paper settings too.</li><li>Set Copies, Color and Orientation as needed. Leave the Windows dialog enabled during initial testing so you can inspect the destination and paper.</li><li>Save printer settings on this device, then run a Test Print. For a PDF destination, select the save location; a saved PDF is not physical output. Copies and the Windows print-dialog option do not apply to the special PDF path.</li></ol>
<h2 id="tcp">Windows or Android: network thermal printer</h2>
<ol><li>Confirm the printer supports ESC/POS raster receipts and is connected to the same reachable network as the device.</li><li>Obtain its IP address from the printer/network setup or the person managing the network. Do not use the web server address unless that machine actually runs your printer emulator.</li><li>Choose <strong>Network thermal printer / emulator</strong>. Enter Printer host / IP address and TCP port. Use 9100 only if that is the port the printer or emulator listens on.</li><li>Choose a thermal paper width, one receipt copy for testing, and enable automatic cutting only if the printer has a cutter.</li><li>Save, check the connection, then print a sample receipt. Inspect the first and last lines, totals, Myanmar text and cut behaviour.</li></ol>
<p>For CrossEscPos on the same Windows computer, 127.0.0.1:9100 is appropriate only when the emulator's TCP listener is running there. On a phone, 127.0.0.1 refers to the phone, not the PC: enter the PC's LAN address instead. Use a trusted network; raw printer traffic is not a secure public-internet service.</p>
<h2 id="bluetooth">Bluetooth thermal printers</h2>
<p><strong>Windows:</strong> pair the printer in Windows first. In MKPOS choose Bluetooth thermal printer, use Open Bluetooth pairing if needed, refresh COM ports, and select the printer's <strong>outgoing</strong> COM port. A random COM port or an incoming port is not equivalent. Save and test. This path requires Bluetooth Classic, not a BLE-only printer.</p>
<p><strong>Android:</strong> pair the printer in Android Settings, open the APK's Printer settings, choose Bluetooth thermal, allow Nearby devices when requested, refresh the paired devices and select the intended printer. A paired device being listed does not prove it supports printing. Use a Classic SPP ESC/POS model and confirm a real receipt. If permission was denied, review the app's permissions in Android Settings.</p>
<h2 id="browser">Web browser printing</h2>
<p>Use Test Print or Print Receipt, allow the MKPOS print window if the browser blocks it, and select the printer or Save as PDF in the browser/system dialog. Review paper size, scale, margins and orientation there. Typing an IP address or COM port does not create a direct connection.</p>
<p>The current browser printer-name field is not proof of a detected local printer. The normal web page cannot use the Windows app's native printing bridge. If you require configured direct TCP or Bluetooth receipts, use the supported native application.</p>
<h2 id="paper">Paper, copies and document layout</h2>
<p>Choose the roll's actual width, not the width you want the receipt to be. Direct thermal output uses common print-head defaults; unusual models still need testing. A4 statements and barcode documents use system printing rather than the direct thermal receipt route. On Windows, the A4 document printer can be configured separately; a blank selection uses the Windows default.</p>
<p>Receipt content and margins belong in Receipt settings. Printer destinations belong in Printer settings. Native profiles are device-specific, so test each checkout computer and phone independently. Keep unfamiliar technical settings at their defaults.</p>
<h2 id="failure">Connection success but nothing prints</h2>
<ol><li>Check power, loaded paper, cover, paper direction and whether the device is paused or showing an error.</li><li>Confirm the saved destination and paper match the intended printer. A successful check only establishes a connection; it does not verify paper output or protocol compatibility.</li><li>Run one test receipt. If it fails, read the full error and note whether the problem occurred before sending or after partial output.</li><li>For TCP, confirm the listener and address. For Bluetooth, confirm pairing, permission and the correct device/port. For system printing, inspect the print queue or print service.</li><li>Before retrying, inspect the output and queue for a partially or fully printed job. Do not generate repeated copies or new sales.</li></ol>
<div class="docs-note">Direct-print success means data was sent, not that MKPOS visually verified paper coming out. A printer check is not a sale, and a printer failure is not a reason to repeat checkout. Use the original saved receipt for reprints.</div>
