<p class="manual-intro">Use Products to maintain the items you sell and the quantities you own. A product's unit settings affect purchases, sales, stock history and estimated profit, so establish them carefully before trading.</p>
<h2 id="add">Add your first product</h2>
<ol><li>Open <strong>Products → Add Product</strong>.</li><li>In Basic Info, enter a clear <strong>Name</strong>, such as Water 600 ml. Use <strong>SKU</strong> for your internal item code and <strong>Barcode</strong> for the code printed on the item. Check that a different product is not already using the same identifier.</li><li>Choose or type a <strong>Category</strong> to group similar items.</li><li>Set <strong>Base / selling unit</strong> to the unit customers buy, such as Bottle. If applicable, enter <strong>Purchase unit</strong>, such as Carton, and the number of base units in one purchase unit.</li><li>Enter <strong>Cost</strong> per base unit, opening <strong>Stock</strong> in base units and the <strong>Low stock alert</strong> threshold.</li><li>Review the Prices section and enter the appropriate selling prices for your configured price types. Save, search for the new item and check its displayed stock and prices.</li></ol>
<h2 id="units">Understand units before entering quantities</h2>
<dl><dt>Base unit</dt><dd>The unit in which stock is counted. If it is Bottle, stock 24 means 24 bottles.</dd><dt>Purchase unit</dt><dd>A buying package containing a known number of base units. Carton can contain 12 bottles.</dd><dt>Conversion</dt><dd>The number of base units in one buying package. For this example enter 12, not a price.</dd><dt>Cost</dt><dd>The product form's cost is per base unit. A 7,200 Ks carton containing 12 bottles corresponds to 600 Ks per bottle.</dd></dl>
<div class="docs-note"><strong>Do not casually change units after trading.</strong> An existing quantity of 24 should not change meaning from bottles to cartons. Ask the person responsible for inventory to review stock and historical records before changing the unit model.</div>
<h2 id="prices">Prices and free goods</h2>
<p>Price types such as Retail and Wholesale let you sell the same item at different rates. They are not quantities. Select the intended price type at the till and verify the amount. Automatic pricing rules, where configured, depend on cost; review prices when buying costs change. Do not assume every imported or newly created price is correct.</p>
<p><strong>FOC</strong> means free of charge. A free item still leaves or enters physical stock. Use the FOC quantity field in the appropriate sale or purchase rather than hiding free goods in a discount.</p>
<h2 id="stock">Correct stock with a traceable adjustment</h2>
<ol><li>Search for the item and open its stock adjustment or stock history action.</li><li>Count the real stock in its base unit and compare with the recorded stock.</li><li>Enter the <strong>difference</strong> in Quantity, not the new total. If MKPOS shows 20 but the count is 18, enter -2. If the count is 23, enter 3.</li><li>Enter a specific Reason, such as “Physical count: two damaged bottles removed”. Review the sign, then submit.</li><li>Check the resulting stock and Movement History. Ask an authorized user if the action is protected.</li></ol>
<p>Record deliveries through New Purchase, not a stock adjustment, when you also need a supplier bill and purchase cost. An adjustment is not a substitute for a purchase or a sale.</p>
<h2 id="find">Find items and low stock</h2>
<p>Use search, Category, Stock status, Exact barcode / SKU or Quick scan. Clear filters when a known item disappears. Review the low-stock and out-of-stock summaries for replenishment, then verify the actual quantities before ordering.</p>
<h2 id="csv">Import or export products with CSV</h2>
<ol><li>Create and verify one product manually. Use <strong>Export</strong> to obtain the current CSV column structure, including your price-type columns.</li><li>Prepare a UTF-8 CSV with Name, SKU, Barcode, Category, Base Unit, Purchase Unit, Units per Purchase Unit, Cost, Stock, Low Stock Alert and the price columns. Keep numeric values plain, and format barcodes as text in your spreadsheet to preserve leading zeros.</li><li>Test <strong>Import</strong> with a small file first. The current importer creates products; it is not an update-existing-products operation.</li><li>Read the result: Added, skipped and failed are different counts. Rows without a name are skipped. Other rows may fail validation; successfully added rows remain added.</li><li>Inspect the results and fix only the remaining rows before retrying. Reimporting the full file can create duplicates or repeated failures. Invalid or missing numeric values can become zero, so inspect costs and prices after import.</li></ol>
<p>A product CSV is not a full business backup. It does not replace sales, payments or stock history.</p>
