<p class="manual-intro">A purchase receives goods into stock and records what the shop owes or has paid to a supplier. Use the supplier's invoice and the physical delivery together; an invoice alone does not prove that all goods arrived.</p>
<h2 id="prepare">Prepare the purchase</h2>
<p>Add the products first with correct base and purchase units. For a credit purchase, add the supplier as a saved supplier before starting. Keep the invoice number, costs, paid quantity, free quantity and payment evidence available.</p>
<h2 id="wizard">Enter a delivery in New Purchase</h2>
<ol><li>Open <strong>New Purchase</strong>. In Basic information, select the Supplier and enter the invoice number or another reference in <strong>Reference note</strong>. Use a saved supplier if any amount will remain unpaid.</li><li>Move to Product selection. Search by name, SKU, barcode or category and select all delivered products.</li><li>In the Quantity form, choose each line's <strong>Buying Unit</strong>. Check whether the quantity means bottles, pieces or cartons before entering a number.</li><li>Enter <strong>Paid Qty</strong>, <strong>FOC Qty</strong> and <strong>Unit Cost</strong>. Paid Qty is the quantity being charged for, not the amount of money paid. Unit Cost is for one selected buying unit.</li><li>Review <strong>Effective Cost</strong> and <strong>Line Total</strong>. Free goods increase received stock without increasing the charged line total.</li><li>In Review and submit, select Payment Method and enter <strong>Paid Now</strong>. It must be between zero and the purchase total. A remaining balance requires a saved supplier.</li><li>Review all lines, received quantities, total and unpaid amount. Resolve any cost warnings before saving once.</li></ol>
<h2 id="example">Example: cartons and free stock</h2>
<p>Suppose Bottle is the base unit, Carton contains 12 Bottles, and one Carton costs 7,200 Ks. You receive 2 paid Cartons and 1 free Carton.</p>
<ul><li>Buying Unit: Carton; Paid Qty: 2; FOC Qty: 1; Unit Cost: 7,200.</li><li>Charged total: 2 × 7,200 = 14,400 Ks.</li><li>Received stock: (2 + 1) × 12 = 36 Bottles.</li><li>Effective cost across the delivery: 14,400 ÷ 36 = 400 Ks per Bottle.</li><li>If Paid Now is 10,000, the unpaid purchase amount is 4,400 Ks.</li></ul>
<div class="docs-note">FOC Qty uses the selected buying unit too. If the supplier gives one free bottle, entering 1 while Buying Unit is Carton represents a whole free carton. Review the unit and received total rather than guessing.</div>
<h2 id="verify">After saving</h2>
<ol><li>Find the new record in <strong>Purchases</strong> or <strong>Transactions</strong> and compare it with the invoice.</li><li>Check stock for at least one delivered product. In the example, its stock should rise by 36 Bottles if nothing else changed.</li><li>Open the supplier account and confirm the unpaid amount and payment record.</li><li>Review affected product costs and automatic selling prices. An unexpected price change is a reason to investigate the entered units and costs.</li></ol>
<h2 id="mistakes">Correct a purchase carefully</h2>
<p>If you chose the wrong unit, quantity, supplier or payment amount, locate the original record and use the authorized Edit Purchase action. Editing or deleting a saved purchase can affect stock and supplier balances; review later sales and payments before proceeding. Do not enter a duplicate purchase with a negative amount as an improvised reversal.</p>
<p>When the save result is uncertain, search by invoice reference and date before submitting again. When a delivery is not recorded, check filters and permissions before assuming it is missing.</p>
