<p class="manual-intro">Reports summarizes recorded activity. It is useful for checking the day, but the numbers are only as reliable as the quantities, costs, payments and expenses entered. A profit estimate is not the amount of cash in the drawer.</p>
<h2 id="period">Choose a reporting period</h2>
<ol><li>Open <strong>Reports</strong>.</li><li>Select Today, This Week, This Month, This Year or All Time. For a custom range, enter From and To, then select <strong>Apply</strong>.</li><li>Confirm the Selected Period shown on the screen. The start date must not be later than the end date.</li><li>Use Refresh after new activity or synchronization. Use <strong>CSV</strong> to download the selected report when available.</li></ol>
<h2 id="meaning">Read the figures correctly</h2>
<dl><dt>Sales</dt><dd>The sales value for the selected period. It includes sales that may not yet be fully paid.</dd><dt>Paid During Sales</dt><dd>Money recorded at checkout against those sales. Later repayments are separate money movements.</dd><dt>Credit Sales</dt><dd>Read alongside paid sales and customer account information. It is not a substitute for today's total outstanding customer balances.</dd><dt>Purchases</dt><dd>Recorded stock purchases in the period. A purchase can be part paid or unpaid.</dd><dt>Expenses</dt><dd>Recorded operating expenses in the selected period.</dd><dt>Net Profit Estimate</dt><dd>An estimate based on the system's recorded sales, costs and expenses. Incorrect costs or missing expenses can distort it.</dd><dt>FOC Issued</dt><dd>Free goods issued in sales. They use stock even though the customer is not charged for that quantity.</dd></dl>
<h2 id="snapshot">Period totals versus current snapshots</h2>
<p>Sections for current accounts and inventory valuation show an <strong>as-of</strong> position. Do not assume that selecting an earlier sales period turns current stock or today's debt into a historical end-of-month snapshot. Read each section's date and label.</p>
<p>Inventory investment value estimates stock at cost; potential sales value estimates its selling value. Neither is money already received. Customer receivables are amounts to collect; supplier payables are amounts to pay.</p>
<h2 id="close">A practical daily closing routine</h2>
<ol><li>Finish or discard unfinished carts. Make sure each completed customer purchase has one saved sale.</li><li>Check every offline device for pending sales. Synchronize and resolve failures before treating the server report as complete.</li><li>Choose Today in Reports and inspect Transactions for unusual totals, duplicates or missing receipts.</li><li>Compare cash, bank and wallet methods separately with actual cash and transfer evidence. Customer repayments, supplier payments, refunds and expenses are not all checkout sales.</li><li>Review customer and supplier balances that changed during the day.</li><li>Check low-stock items and investigate unexpected stock adjustments.</li><li>Export the report if needed, create a business backup when permitted, and sign out of shared tills.</li></ol>
<h2 id="cash">Example: why sales and cash differ</h2>
<p>You sell 30,000 Ks, receive 25,000 at checkout, and leave 5,000 on credit. You also collect 2,000 from an older debt and pay a 3,000 cash expense. If all these payments were cash and there were no other movements, cash increased by 24,000, not 30,000. Your drawer also contains its opening float. Compare that float and other real movements separately.</p>
<h2 id="investigate">Investigate differences before changing data</h2>
<p>Check date filters, payment methods, delayed offline synchronization, old debt payments, duplicate records, FOC quantities and wrong purchase units. Find the source transaction first. Do not add a false sale, expense or adjustment just to make a report match an expected number.</p>
