<p class="manual-intro">Use Sell for a new customer purchase. Completing a sale saves a business transaction; printing is a separate action. Always verify whether a sale was saved before attempting it again after an error.</p>
<h2 id="prepare">Before serving a customer</h2>
<ul><li>Check that you are signed into the correct shop and that the printer is ready.</li><li>Confirm whether you are using online Sell or Offline POS. Offline credit is not available.</li><li>Use the correct price type, such as Retail. Check that no previous customer's unfinished items remain in the cart.</li></ul>
<h2 id="cart">1. Build and check the cart</h2>
<ol><li>Click <strong>Barcode Scan</strong>, scan the label and press Enter if the scanner does not send Enter automatically. Use Focus Scan when you need to put the cursor back in the scan field.</li><li>Alternatively, search by product name, SKU or barcode, or filter by category, then choose the product.</li><li>Check the cart product name, price type and unit price. Adjust Quantity to the number of base selling units requested. Repeated scans can increase quantity, so watch the cart as you scan.</li><li>If giving free items, enter their FOC quantity where available. Confirm both the paid quantity and free quantity.</li><li>Remove an unwanted line using its remove action. Review all quantities before selecting <strong>Checkout</strong>.</li></ol>
<h2 id="payment">2. Enter discount and payment</h2>
<ol><li>Enter any allowed <strong>Discount</strong>. The checkout discount is an amount, not a percentage: entering 500 subtracts 500 from the subtotal.</li><li>For a fully paid walk-in sale, a named Customer is optional. For any unpaid balance, select a saved customer.</li><li>Select the <strong>Payment Method</strong> that actually received the money. Naming a method KPay or a bank does not transfer money; verify the payment separately.</li><li>Enter <strong>Paid Amount</strong> deliberately. Check the displayed Total, Unpaid and, if present, Change.</li><li>Choose <strong>Complete Sale</strong> once. Wait for the completion message before starting another sale.</li></ol>
<h2 id="examples">Worked examples</h2>
<dl><dt>Exact payment</dt><dd>Three bottles at 1,000 Ks each: subtotal 3,000, discount 0, total 3,000. Enter paid amount 3,000. Unpaid should be 0.</dd><dt>Cash change</dt><dd>For the same total, a customer gives 5,000. Enter 5,000; Change should be 2,000. Return the change. The sale payment recorded against the sale is capped at the total.</dd><dt>Discount</dt><dd>Subtotal 3,000 minus discount 500 gives total 2,500. If the customer pays 2,500, Unpaid should be 0.</dd><dt>Part payment</dt><dd>Total 3,000 and paid amount 1,000 leave 2,000 unpaid. Select the correct customer before completing; the balance belongs to that account.</dd></dl>
<h2 id="receipt">3. Print and verify the saved sale</h2>
<p>After completion, use <strong>Print Receipt</strong>. In a browser, allow the print window and choose the destination in the print dialog. In a native app, use the saved printer profile. Verify the receipt number, items, total and payment on the output.</p>
<p>For an older receipt, open <strong>Transactions</strong>, locate the sale and use Print or Reprint. The Sell screen's last-receipt action is not a search of all historical receipts; verify the receipt identity before handing it to a customer.</p>
<div class="docs-note"><strong>Printing failed does not mean the sale failed.</strong> Check Transactions for the saved sale and reprint that receipt. Do not complete a second sale simply because the printer was offline. If the connection failed during checkout and the result is uncertain, search for the transaction before retrying.</div>
<h2 id="handover">Finish and hand over the till</h2>
<p>Complete or deliberately discard the unfinished cart before leaving. On web and Windows, <strong>Sign out</strong> is in the scan toolbar, including for sell-only staff. An unfinished cart requires confirmation before sign-out. Never give another cashier your session or the owner's password.</p>
<h2 id="errors">Common checkout messages</h2>
<ul><li><strong>Add products to cart first:</strong> search or scan an item before checkout.</li><li><strong>Quantity greater than zero:</strong> enter a valid positive quantity or remove the line.</li><li><strong>Unpaid amount requires selecting a customer:</strong> select the debtor, or correct Paid Amount if the customer already paid in full.</li><li><strong>Insufficient stock or changed data:</strong> refresh and check physical stock with the owner. Do not inflate stock to bypass the error.</li></ul>
