<p class="manual-intro">Settings controls business identity, receipt content, payment labels, pricing rules and other preferences. Save the section you changed before leaving it. Test the result with a sample receipt or a known product.</p>
<h2 id="shop">Shop and account details</h2>
<p>Open <strong>Settings → Shop</strong>. Enter Shop Name, Shop Title, Address, Phone and Currency, then Save. Check spelling and phone numbers on a receipt preview. A currency label is not an exchange-rate conversion tool: changing it does not convert existing amounts.</p>
<p>In <strong>Account</strong>, review owner name and email. Account changes require the current password where shown. To change password, enter the new password and confirmation; leaving the new password blank keeps it unchanged. Never share passwords or include them in screenshots.</p>
<h2 id="receipt">Receipt content and layout</h2>
<ol><li>Open <strong>Receipt</strong>, not Printer, to change receipt text and layout.</li><li>Enter Footer Text, such as opening hours or a short thank-you message.</li><li>Adjust Header Alignment, Left Margin, Right Margin, Header Size, Body Size and Line Spacing only if the preview needs a change. Margins are in millimetres; font sizes are in points.</li><li>Use the preview to inspect the shop details, product names and totals. It contains sample data, not proof that a sale was saved.</li><li>Use <strong>Test Print</strong> to inspect actual output, then Save the intended settings. Check paper width in Printer settings too.</li></ol>
<p>Begin with the existing defaults. If text is clipped, first match the loaded paper width and printer settings. Making fonts tiny to compensate for the wrong paper is not a reliable fix. Long product names and Myanmar text are useful test cases.</p>
<h2 id="printer">Printer is a separate device setup</h2>
<p>Use <strong>Settings → Printer</strong> for connection type, printer destination and paper. Native printer profiles are local to that device. Configuring the Windows till does not configure an Android phone. See the Printing guide for installed printers, TCP and Bluetooth.</p>
<h2 id="payments">Payment methods</h2>
<p>Open <strong>Payments</strong> and maintain the names cashiers should choose. Keep Cash, bank and wallet labels clear and consistent. Save, then verify the options in checkout. These labels record how money was received; adding a payment method does not integrate or initiate a bank transfer.</p>
<h2 id="pricing">Price types and automatic pricing</h2>
<p>Open <strong>Prices</strong>. A price type identifies a selling rate, such as Retail or Wholesale. Manual pricing uses amounts you maintain. Automatic pricing exposes Markup %, Round up to and Minimum profit settings. Review the computed prices on a known product after changing a rule.</p>
<ul><li>Markup is based on cost, not a discount for the customer.</li><li>Rounding can make a computed price higher than the unrounded amount.</li><li>A minimum-profit rule can raise a price beyond the simple markup result.</li><li>Changing a rule can affect many products. Review the result before staff resume selling.</li><li>A price type used by products may not be deletable. Update dependencies deliberately instead of renaming types repeatedly.</li></ul>
<h2 id="language">Language, security and maintenance</h2>
<p><strong>Language</strong> offers English and Myanmar. Translated labels may differ from the English wording in this manual. <strong>Security</strong> maintains the Admin PIN; a blank PIN field keeps an existing PIN. <strong>Data</strong> handles business backup and restore. <strong>About</strong> helps identify the application version and data location.</p>
<p>Before leaving Settings, check that a success message appeared. If a save failed, do not assume the preview or edited fields have been persisted.</p>
