<p class="manual-intro">Start here if you have never used MKPOS. MKPOS connects a sale to stock, customer balances and reports. The goal of setup is to make those records agree with your real shop before a cashier starts serving customers.</p>
<div class="docs-note"><strong>About this manual.</strong> The English labels below follow the web and Windows business application. Mobile uses smaller, separate screens; the same business concepts apply, but buttons may be in a menu or on another page. Your installed version, account permissions and plan determine which actions are available. Examples are practice numbers, not transactions to enter into a live shop.</div>
<h2 id="before">1. Prepare before creating records</h2>
<ul><li>Have the correct business name, owner email and a private password ready.</li><li>Collect your product list, barcodes, selling prices, supplier invoices and a physical stock count.</li><li>Decide the smallest unit you sell for each product: Piece, Bottle, Pack or another unit. Write down how many of those units a carton contains.</li><li>Decide who can sell, manage stock and edit financial records. Use individual staff accounts.</li><li>Have a working internet connection for account setup and initial data loading. Offline POS must be prepared separately.</li></ul>
<h2 id="account">2. Create or join the correct business</h2>
<ol><li>On the public website select <strong>Start free trial</strong>, then complete <strong>Create your business</strong>.</li><li>Enter Business name, Owner name, Email address, Password and Confirm password. Passwords must contain at least eight characters. Use a unique password that you do not share with cashiers.</li><li>Select <strong>Create business account</strong> once and wait for the result. Correct any highlighted validation errors.</li><li>If the business already exists, use <strong>Sign in</strong> with its account instead. A staff member should receive an account from the owner, not register a second business.</li><li>After signing in, confirm the displayed business and user name. A fresh, empty catalogue can mean you are in a different business; do not immediately import everything again.</li></ol>
<h2 id="navigation">3. Understand the workspace</h2>
<p>The main navigation opens Sell, Products, Purchases, New Purchase, Suppliers, Customers, Expenses, Transactions, Reports, Billing, Settings and Access when your account permits them. Sell is the checkout interface. Products manages the catalogue; Transactions finds saved activity; Reports summarizes it.</p>
<p>On a small screen, open the navigation menu or use the page's back button. Long lists may have page controls or load more items as you scroll. A search or date filter can hide records without deleting them. Clear filters before concluding that data is missing.</p>
<h2 id="setup-order">4. Follow this setup order</h2>
<ol><li>Open <strong>Settings → Shop</strong>, enter contact details and currency, then save.</li><li>Review <strong>Payments</strong> and <strong>Prices</strong> in Settings. Use names staff will recognize, such as Cash and Retail.</li><li>Create a few products in <strong>Products</strong>. Verify units, cost, selling price and opening stock before adding the rest.</li><li>Add regular customers and suppliers. Do not invent old sales just to force an opening balance; ask the owner to agree a migration method for historical debts.</li><li>Configure <strong>Receipt</strong> content and <strong>Printer</strong> connection separately. Run a test receipt.</li><li>Set up roles and staff in <strong>Access</strong>, then test a staff sign-in.</li><li>Read the selling guide and complete your first real sale only after checking the cart and payment.</li></ol>
<h2 id="first-example">5. Follow one product through the system</h2>
<p>Example: you sell water by Bottle at 1,000 Ks. One Carton contains 12 Bottles. If you already own 24 Bottles at launch, opening Stock is 24, not 2. Selling 2 Bottles reduces stock to 22. Receiving one more Carton adds 12, giving 34. These numbers assume no other sales, purchases, free items or adjustments.</p>
<p><strong>Avoid double counting:</strong> either include goods in opening stock or record the incoming purchase that adds them. Doing both for the same goods increases stock twice.</p>
<h2 id="ready">Ready-to-open checklist</h2>
<ul><li>Correct business and account shown; payment methods and prices checked.</li><li>Five sample products match the physical count, units and barcode labels.</li><li>A test receipt is readable; printer settings are saved on this device.</li><li>The cashier can sign in and sign out without using the owner's password.</li><li>You know how to find a saved sale before retrying after an error.</li></ul>
