<p class="manual-intro">Suppliers are the businesses or people who deliver your stock. Their accounts connect purchases, money paid to them and money returned by them. Use supplier accounts for stock-related bills, not the customer account list.</p>
<h2 id="create">Add and identify a supplier</h2>
<ol><li>Open <strong>Suppliers → Add Supplier</strong>.</li><li>Enter Supplier Name, Phone, Contact Person, Address and a useful Note, such as your account reference with that supplier.</li><li>Save and search for the supplier to confirm the details. Check for an existing record before adding another.</li><li>Select this saved supplier when entering a purchase. A credit purchase must be linked to a saved supplier.</li></ol>
<h2 id="review">Review the supplier account</h2>
<p>Choose <strong>View supplier</strong> from the supplier's actions. The Overview and history sections help you inspect purchases and payment records. Filter purchase history by purchase ID or note and From / To dates, then Apply. Clear the filters to inspect older activity.</p>
<p>Compare the current balance with the supplier's invoice list and your payment evidence. A purchase's unpaid amount is only one part of the supplier's whole account.</p>
<h2 id="pay">Pay an outstanding supplier bill</h2>
<ol><li>Open the correct supplier and choose <strong>Record payment</strong>.</li><li>Select Direction <strong>Shop pays supplier</strong>.</li><li>Enter the positive Amount, Payment method and Note. Include the transfer reference or invoice numbers so someone else can trace the payment later.</li><li>Check the actual cash handover or transfer confirmation. Saving this form records the payment; it does not send money to the supplier.</li><li>Submit once, inspect the new payment record and verify the current balance.</li></ol>
<p>Example: the supplier balance is 14,400 Ks and you pay 10,000. It should reduce to 4,400 if there are no other changes. Do not record again an amount already entered as Paid Now on the original purchase.</p>
<h2 id="refund">Record a supplier refund</h2>
<p>Select <strong>Supplier refunds shop</strong> when money moves back to your business. Keep the reason in the note. This direction is not a supplier payment and does not by itself record returned goods. If stock is being returned too, have the owner review the purchase and stock consequences rather than assuming a money record reverses the delivery.</p>
<h2 id="corrections">Changes and account checks</h2>
<p>Edit supplier updates contact information. To correct a saved payment, locate it in Transactions and use the authorized Edit Payment action. Deletion is a record-changing operation, not a way to settle an unpaid bill. After a correction, recheck both history and the balance.</p>
<ul><li>A positive amount in the wrong direction has the opposite business meaning. Always read Direction before saving.</li><li>If a supplier reports a different balance, compare each invoice and payment, including part payments.</li><li>Do not create a second supplier account just because a balance is unexpected.</li><li>Use the original invoice reference on purchases and payment notes to make reconciliation easier.</li></ul>
