<p class="manual-intro">Transactions is the place to find already saved activity. Use it to verify an uncertain save, inspect a receipt, reprint, or correct a record. Start with View before using Edit or Delete.</p>
<h2 id="find">Find the right record</h2>
<ol><li>Open <strong>Transactions</strong> and select the relevant section for sales, purchases, customer payments or supplier payments.</li><li>Open the filters and enter a search term or reference, From and To dates, and available Type, Method or Direction filters.</li><li>Select <strong>Apply Filters</strong>. Use Refresh to reload current data; Clear removes restrictions that might hide the record.</li><li>Inspect the record's date, receipt or purchase reference, customer or supplier, items and amount. Similar totals alone are not enough to identify a duplicate.</li><li>Open the detail view before deciding what action is needed.</li></ol>
<h2 id="reprint">Reprint an existing sale</h2>
<p>Use the sale's Print receipt action or <strong>Reprint</strong> in its detail view. Check the receipt number and destination printer. Reprinting should use the existing sale; do not recreate the sale in Sell. If a printer partially printed, check what was produced before printing another copy.</p>
<h2 id="edit-sale">Correct a saved sale</h2>
<ol><li>Obtain the owner's approval and locate the original sale.</li><li>Open <strong>Edit Sale</strong>. Review payment status, payment method, customer, discount, paid amount and the item lines.</li><li>Change only what is incorrect. Check paid and FOC quantities, selected prices, total and unpaid balance together.</li><li>Provide the Admin PIN if requested. A PIN is not a substitute for having permission to access the action.</li><li>Select <strong>Update Sale</strong>, then verify the sale, affected product stock and customer account. Print the corrected receipt if required.</li></ol>
<div class="docs-note">Editing historical sales is not a routine checkout step. A later payment may already exist against the customer's account. Review the complete history before reducing a sale or changing its customer.</div>
<h2 id="other-edits">Correct purchases and payments</h2>
<p><strong>Edit Purchase</strong> can change supplier, note, payment information and item details, including units and costs. Check physical stock and supplier balances afterward. <strong>Edit Payment</strong> can change the account, direction, amount, method or note. Review both the previous and new account if moving a payment.</p>
<p>Example: a 2,000 customer repayment was entered as 20,000. Correct that payment record rather than inventing a 18,000 opposite-direction payment merely to hide the typo. Confirm the source evidence and the resulting account balance.</p>
<h2 id="delete">Deletion and uncertain results</h2>
<ul><li>Delete only a wrong or duplicate record, with authority and a recorded reason.</li><li>Read the confirmation and any PIN prompt. Related stock, account and report values can change.</li><li>Do not use Delete as a generic product-return workflow. Returning goods and refunding money are separate real-world events.</li><li>If a request times out, refresh and inspect the record before repeating the action. The server may already have completed it.</li><li>After any edit or deletion, recheck the reporting period and preserve the original business evidence.</li></ul>
