<p class="manual-intro">Start with the smallest safe check. Refreshing a list is different from resetting app data. When a save result is uncertain, check for the saved record before trying again.</p>
<h2 id="missing">A product or record is missing</h2>
<ol><li>Confirm the business name and signed-in user.</li><li>Clear search, category, date, payment and stock filters. Check other pages or scroll further.</li><li>Refresh the list while online.</li><li>Check whether the record exists only on another device's pending offline queue.</li><li>If a whole module is absent, ask the owner to review the account's role rather than creating another account or importing again.</li></ol>
<h2 id="save">A save failed, timed out or showed an error</h2>
<p>Copy the useful error text and note the action and time. Check connectivity, then search the relevant Transactions or list screen for the new record. A server save can succeed even when a later receipt or refresh request fails. Do not click Save repeatedly, create duplicate payments or repeat checkout without checking.</p>
<h2 id="print">The printer check passed but printing failed</h2>
<p>Check the selected device, paper, cover and protocol. A connection check only verifies connectivity; a real receipt also requires rendering and compatible printer commands. Inspect the queue and actual output before retrying. Use the Printing guide's method-specific steps. Reprint the original sale rather than selling the items again.</p>
<h2 id="blank">The app is blank or will not open</h2>
<p>Record the app version, address if using a browser, and the visible error. Check that the intended server is running and reachable. A normal page reload may help after an update, but first consider whether an unfinished form or cart will be lost. Do not clear site storage, reset app data or uninstall a device with pending sales. Give the administrator the error text; a code or server problem is not fixed by changing product records.</p>
<h2 id="balances">Stock or balances look wrong</h2>
<ul><li><strong>Stock:</strong> compare base units with buying units, opening stock, purchases, sales, FOC quantities and adjustments. Check for a delivery recorded twice.</li><li><strong>Customer balance:</strong> check unpaid sales, later payments and payment direction. Do not record checkout money again as a repayment.</li><li><strong>Supplier balance:</strong> check purchase Paid Now, subsequent payments and supplier refunds.</li><li><strong>Reports:</strong> compare the selected period with current-as-of account and inventory sections. Synchronize pending work first.</li></ul>
<h2 id="support">What to send to support</h2>
<p>Provide the application type (web, Windows or Android), version, exact action, error text, approximate time, affected receipt/reference, whether you were online, and whether a record or paper output already exists. For printing, include model, connection type and paper width. Mask customer details in screenshots and never include passwords, Admin PINs, payment credentials or full backup files in public messages.</p>
<h2 id="glossary">Plain-language glossary</h2>
<dl><dt>SKU</dt><dd>Your internal product identifier, which may differ from the printed barcode.</dd><dt>Base unit</dt><dd>The unit used to count and sell the product.</dd><dt>Conversion</dt><dd>How many base units are in one purchase unit.</dd><dt>FOC</dt><dd>Free of charge: goods received or given without charging for that quantity.</dd><dt>Subtotal</dt><dd>The sum of charged item lines before the checkout discount.</dd><dt>Credit</dt><dd>A sale or purchase amount that has not yet been fully paid.</dd><dt>Receivable</dt><dd>Money the business is still to collect from customers.</dd><dt>Payable</dt><dd>Money the business is still to pay to suppliers.</dd><dt>Stock adjustment</dt><dd>A recorded increase or decrease used to correct physical inventory differences.</dd><dt>Pending sale</dt><dd>A locally saved sale awaiting server synchronization.</dd><dt>Sync</dt><dd>Sending eligible queued local sales to the server and checking the outcome.</dd><dt>ESC/POS</dt><dd>A family of thermal-printer commands; support must match the printer's capabilities.</dd><dt>TCP port</dt><dd>The numbered network endpoint used by a printer service, commonly 9100 for raw thermal printing.</dd><dt>COM port</dt><dd>A Windows serial endpoint, sometimes provided by a paired Bluetooth Classic printer.</dd><dt>Restore</dt><dd>Recovering records from a backup, potentially replacing the current data.</dd></dl>
